#!/system/xbin/bash
# Bersihkan Layar

# Variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\e[1;36m'
red='\e[1;31m'

figlet Tools | lolcat

echo "__________________________________________________" |lolcat
echo "| Author   : Tp.T0kk3 $cyan                   |" |lolcat
echo "|                                                |" |lolcat
echo "| Friend   : Mr.Grim - Sandi LulzSec01 - Mr.CL4Y |" |lolcat
echo "|                Zee - Mr.XTOP4NG - Rion Ops     |" |lolcat
echo "|                                                |" |lolcat
echo "| Team     : Lul'zSec Indo Team - We Are Otaku   |" |lolcat
echo "|               Kutu Buku Cyber Team Network     |" |lolcat
echo "|                                                |" |lolcat
echo "| Contact  : squadsuicide86@gmail.com $red    |" |lolcat
echo "__________________________________________________" |lolcat

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
echo -e $cyan"[#]> Thanks"
sleep 1
echo ""
echo -e $white"[#]> see you gaes :)..."
sleep 1
exit
}
echo $cyan" DIPILIH COK :)"
echo ""
echo $cyan" Kumpulan Tools Spammer"
echo ""
echo $b "01) SpammerL00L${enda}"
echo "============================" | lolcat
echo $r "02) SpamBukaLapak${enda}"
echo "============================" | lolcat
echo $g "03) GcoSpam${enda}"
echo "============================" | lolcat
echo $c "04) SpazSMS${enda}"
echo "============================" | lolcat
echo $r "05) LITESPAM${enda}"
echo "============================" | lolcat
echo $b "06) SpammerGrab${enda}"
echo "============================" | lolcat
echo $b "07) LiteOTP${enda}"
echo "============================" | lolcat
echo $b "08) SpamTsel${enda}"
echo "============================" | lolcat
echo $b "09) HackingSpammer${enda}"
echo "============================" | lolcat
echo $b "10) SdvSpam${enda}"
echo "============================" | lolcat
echo $r "00) Exit${endc}"
echo ""
echo    "╭─T0kk3"|lolcat
read -p "╰─#" bro;

if [ $bro = 1 ] || [ $bro = 01 ]
then
clear
echo $red" Installing SpammerL00L "
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install git
git clone https://github.com/MrL00L/Spammer-L00L.git
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd Spammer-L00L "
echo " $ php Spammer.php "
echo ""
echo $cyan" BERHASIL_COK "
fi

if [ $bro = 2 ] || [ $bro = 02 ]
then
clear
echo $red" Installing SpamBukaLapak "
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install git
git clone https://github.com/siputra12/prank
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd prank "
echo " $ chmod +x * "
echo " Untuk Spam Telepon Ketik $ php call.php "
echo " Untuk Spam WhatsApp Ketik $ php wa.php "
echo ""
echo $cyan" BERHASIL_COK "
fi

if [ $bro = 3 ] || [ $bro = 03 ]
then
clear
echo $red" Installing GcoSpam "
sleep 1
pkg update && pkg upgrade
apt install git
git clone https://github.com/Amriez/gcospam
cd gcospam
sh install.sh
echo ""
echo " Cara Menjalankannya Ketik "
echo " $ cd gcospam "
echo " $ sh gco.sh "
echo ""
echo $cyan" BERHASIL_COK "
fi

if [ $bro = 4 ] || [ $bro = 04 ]
then
clear
echo $red" Installing SpazSMS "
sleep 1
pkg update && pkg upgrade
pkg install python2
pkg install git
git clone https://github.com/Gameye98/SpazSMS
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd SpazSMS "
echo " Setelah Itu nanti akan ada 3 Pilihan Spam,, di sini saya Menggunakan spam lite.py "
$ python2 lite.py
$ python2.7 lite.py --sms 628*******
Catatan: --sms bisa kalian ganti dengan --call
Dan untuk Tool spam yg lain nya bisa kalian kembangkan sendiri
5) git clone https://github.com/Rajkumrdusad/Tool-X
echo -e "${y} Installer Tool-X..."
echo -e "${y} cd Tool-X"
echo -e "${y} sh install.aex"
cd /data/data/com.termux/files/home/Tool-X
bash /data/data/com.termux/files/home/Tool-X/sh install.aex

;;


6) echo "created by : 0daysecurity98" | lolcat
exit
;;

*) echo "sorry, pilihan yang anda cari tidak ada"
esac
done
done
