#!/bin/bash
#version 1.0

# Variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\e[1;36m'
red='\e[1;31m'

figlet Tools | lolcat

echo -e  "_____________________________________________________________"
echo -e  "Author   : Tp.T0kk3 $cyan         " |lolcat
echo -e  " " |lolcat
echo -e  "Friend   : Mr.Grim - Sandi LulzSec01 - Mr.CL4Y " |lolcat
echo -e  "                Zee - Mr.XTOP4NG - Rion Ops    " |lolcat
echo -e  " " |lolcat
echo -e  "Team     : Lul'zSec Indo Team - We Are Otaku " |lolcat
echo -e  "              Kutu Buku Cyber Team Network " |lolcat
echo -e  " " |lolcat
echo -e  "Contact  : squadsuicide86@gmail.com $red " |lolcat
echo -e  "_____________________________________________________________"

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
echo -e $cyan"[#]> Thanks"
sleep 1
echo ""
echo -e $white"[#]> see you gaes :)..."
sleep 1
exit
}

lagi=1
while [ $lagi -lt 0 ];
do
echo ""
echo -e $b "1.  SpammerL00L${enda}";
echo -e "============================" | lolcat
echo -e $r "2.  SpamBukaLapak${endc}";
echo -e "============================" | lolcat
echo -e $g "3.  GcoSpam${endc}";
echo -e "============================" | lolcat
echo -e $c "4.  SpazSMS${endc}";
echo -e "============================" | lolcat
echo -e $r "5.  LITESPAM${endc}";
echo -e "============================" | lolcat
echo -e $b "6.  SpammerGrab${enda}";
echo -e "============================" | lolcat
echo -e $b "7.  LiteOTP${enda}";
echo -e "============================" | lolcat
echo -e $b "8.  SpamTsel${enda}";
echo -e "============================" | lolcat
echo -e $b "9.  HackingSpammer${enda}";
echo -e "============================" | lolcat
echo -e $b "10. SdvSpam${enda}";
echo -e "============================" | lolcat
echo -e $r "0.  Exit${endc}";
echo ""
echo -e "╭─T0kk3"|lolcat
read -p "╰─#" pil;

# SpammerL00L

case $pil in
1) pkg install php
   pkg install git
   git clone https://github.com/MrL00L/Spammer-L00L.git
echo -e  "${y} {1} Masukkan Web${endc}:"
read web
nmap $web
echo

;;

# admin-finder

2) git clone  https://github.com/the-c0d3r/admin-finder.git
echo -e "${y} cara menggunakan admin finder"
echo -e "${y} cd admin-finder"
echo -e "${y} python admin-finder.py"
cd /data/data/com.termux/files/home/admin-finder/
python2 /data/data/com.termux/files/home/admin-finder/admin-finder.py
echo

;;

#RED_HAWK

3) git clone https://github.com/Tuhinshubhra/RED_HAWK
echo -e "${y} Installer RED_HAWK..."
echo -e "${y} cd RED_HAWK"
echo -e "${y} php RED_HAWK.php"
cd /data/data/com.termux/files/home/RED_HAWK/
php /data/data/com.termux/files/home/RED_HAWK/ RED_HAWK.php

;;

#Lazymux

4) git clone https://github.com/Gameye98/Lazymux
echo -e "${y} Installer Lazymux..."
echo -e "${y} cd Lazymux"
echo -e "${y} python lazymux.py"
cd /data/data/com.termux/files/home/Lazymux/
python2 /data/data/com.termux/files/home/Lazymux/ lazymux.py

;;

#Tools-X

5) git clone https://github.com/Rajkumrdusad/Tool-X
echo -e "${y} Installer Tool-X..."
echo -e "${y} cd Tool-X"
echo -e "${y} sh install.aex"
cd /data/data/com.termux/files/home/Tool-X
bash /data/data/com.termux/files/home/Tool-X/sh install.aex

;;


6) echo "created by : 0daysecurity98" | lolcat
exit
;;

*) echo "sorry, pilihan yang anda cari tidak ada"
esac
done
done
