#!/system/xbin/bash
# Bersihkan Layar

# Variables
b='\033[1m'
u='\033[4m'
bl='\E[30m'
r='\E[31m'
g='\E[32m'
bu='\E[34m'
m='\E[35m'
c='\E[36m'
w='\E[37m'
endc='\E[0m'
enda='\033[0m'
blue='\e[1;34m'
cyan='\033[36;1m'
red='\033[31;1m'

figlet Erick Gans | lolcat

echo "==================================================" |lolcat
echo "| Author   : Tp.T0kk3                            |" |lolcat
echo "|                                                |" |lolcat
echo "| Friend   : Mr.Grim - Sandi LulzSec01 - Mr.CL4Y |" |lolcat
echo "|                Zee - Mr.XTOP4NG - Rion Ops     |" |lolcat
echo "|                                                |" |lolcat
echo "| Team     : Lul'zSec Indo Team - We Are Otaku   |" |lolcat
echo "|               Kutu Buku Cyber Team Network     |" |lolcat
echo "|                                                |" |lolcat
echo "| Contact  : squadsuicide86@gmail.com            |" |lolcat
echo "==================================================" |lolcat

###################################################
# CTRL + C
###################################################
trap ctrl_c INT
ctrl_c() {
clear
echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "
echo -e $cyan"[#]> Thanks"
sleep 1
echo ""
echo -e $white"[#]> See You Cok :)..."
sleep 1
exit
}
echo " DIPILIH COK :) " | lolcat
echo ""
echo " Kumpulan Tools Spammer " | lolcat
echo ""
echo $b "01) SpammerL00L${enda}"
echo "============================" | lolcat
echo $b "02) SpamBukaLapak${enda}"
echo "============================" | lolcat
echo $b "03) GcoSpam${enda}"
echo "============================" | lolcat
echo $b "04) SpazSMS${enda}"
echo "============================" | lolcat
echo $b "05) LITESPAM${enda}"
echo "============================" | lolcat
echo $b "06) SpammerGrab${enda}"
echo "============================" | lolcat
echo $b "07) SpamBomMAIL${enda}"
echo "============================" | lolcat
echo $b "08) SpamTsel${enda}"
echo "============================" | lolcat
echo $b "09) HackingSpammer${enda}"
echo "============================" | lolcat
echo $b "10) SdvSpam${enda}"
echo "============================" | lolcat
echo $b "00) Exit${enda}"
echo ""
echo    "╭─T0kk3"|lolcat
read -p "╰─#" bro;

if [ $bro = 1 ] || [ $bro = 01 ]
then
clear
echo " Installing SpammerL00L " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install git
git clone https://github.com/MrL00L/Spammer-L00L.git
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd Spammer-L00L "
echo " $ chmod +x * "
echo " $ php Spammer.php "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 2 ] || [ $bro = 02 ]
then
clear
echo " Installing SpamBukaLapak " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install git
git clone https://github.com/siputra12/prank
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd prank "
echo " $ chmod +x * "
echo " Untuk Spam Telepon Ketik $ php call.php "
echo " Untuk Spam WhatsApp Ketik $ php wa.php "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 3 ] || [ $bro = 03 ]
then
clear
echo " Installing GcoSpam " | lolcat
sleep 1
pkg update && pkg upgrade
apt install git
git clone https://github.com/Amriez/gcospam
cd gcospam
sh install.sh
echo ""
echo " Cara Menjalankannya Ketik "
echo " $ cd gcospam "
echo " $ chmod +x * "
echo " $ sh gco.sh "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 4 ] || [ $bro = 04 ]
then
clear
echo " Installing SpazSMS " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install python2
pkg install git
git clone https://github.com/Gameye98/SpazSMS
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd SpazSMS "
echo " $ chmod +x * "
echo " Setelah Itu nanti akan ada 3 Pilihan Spam,, di sini saya Menggunakan spam lite.py "
echo " $ python2 lite.py "
echo " $ python2 lite.py --sms NoTarget "
echo " NOTE : --sms bisa kalian ganti dengan --call "
echo " Dan untuk Tool spam yg lain nya bisa kalian kembangkan sendiri "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 5 ] || [ $bro = 05 ]
then
clear
echo " Installing LITESPAM " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install toilet
pkg install git
git clone https://github.com/4L13199/LITESPAM
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd LITESPAM "
echo " $ chmod +x * "
echo " $ sh LITESPAM.sh "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 6 ] || [ $bro = 06 ]
then
clear
echo " Installing SpammerGrab " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install python2
pip2 install requests
pkg install git
git clone http://github.com/p4kl0nc4t/Spammer-Grab
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd Spammer-Grab "
echo " $ chmod +x * "
echo " $ python2 spammer.py no hp korban --delay 30 "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 7 ] || [ $bro = 07 ]
then
clear
echo " Installing SpamBomMAIL " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install php
pkg install wget
wget http://files-store.theprivat.ml/uploads/bom-mall.zip
unzip bom-mall.zip
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd bom-mall "
echo " $ chmod +x * "
echo " $ php run.php "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 8 ] || [ $bro = 08 ]
then
clear
echo " Installing SpamTsel " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install curl 
pkg install php 
curl -s http://files-store.theprivat.ml/uploads/bombtsel.txt > bombtsel.php 
chmod 777 bombtsel.php
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd bombtsel "
echo " $ php bombtsel.php "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 9 ] || [ $bro = 09 ]
then
clear
echo " Installing HackingSpammer " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install python2
pkg install php
pip2 install requests
pkg install nano
pkg install git
git clone https://github.com/Senitopeng/SpamSms.git
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd SpamSms "
echo " $ chmod +x * "
echo " $ python2 mantan.py "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 10 ] || [ $bro = 10 ]
then
clear
echo " Installing SdvSpam " | lolcat
sleep 1
pkg update && pkg upgrade
pkg install git
git clone https://github.com/mrmsdv/sdvspam.git
cd sdvspam
sh install.sh
echo ""
echo " Cara Menjalankannya Ketik : "
echo " $ cd sdvspam "
echo " $ chmod +x * "
echo " $ sh sdv.sh "
echo ""
sleep 1
echo $cyan" GAGAL_COK "
sleep 1
echo $cyan" Tapi Bohong Wkwk :D "
fi

if [ $bro = 00 ] || [ $bro = 00 ]
then
echo " Copyright © 2018 ErickGansSangad All Right Reserved " | lolcat
exit
fi
